site_name: Tarea 4 C17105

nav:
  - Reference: ode.md
  - Ejemplos: ejemplos.md
  - Index: ondex.md
theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings

extra_javascript:

  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences
